# Generated by Django 4.1.7 on 2023-04-19 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='maintenance_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='DeviceMaintenanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.devices')),
            ],
        ),
    ]
