# Generated by Django 4.1.7 on 2023-04-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devices_maintenance_date_devicemaintenancehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='maintenance_date',
            field=models.DateField(),
        ),
    ]
