# Generated by Django 4.1.7 on 2023-07-30 08:30

from django.db import migrations, models
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_devices_maintenance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='maintenance',
            field=recurrence.fields.RecurrenceField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='maintenance_date',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
