# Generated by Django 4.1.7 on 2023-07-30 11:18

from django.db import migrations
import django.utils.timezone
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_devices_maintenance_alter_devices_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='maintenance',
            field=recurrence.fields.RecurrenceField(default='',blank=True, null=True),
            preserve_default=False,
        ),
    ]
