# Generated by Django 4.1.7 on 2023-08-01 18:06

from django.db import migrations
import recurrence.fields


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_alter_devices_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='maintenance',
            field=recurrence.fields.RecurrenceField(blank=True, default='', null=True),
        ),
    ]
