# Generated by Django 4.1.7 on 2023-08-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_devices_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Check RMU manometer gas reading. It should be in the green zone',
            field=models.BooleanField(blank=True, db_column='check_5', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Check fire extinguisher expiry date details.',
            field=models.BooleanField(blank=True, db_column='check_9', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Check for any abnormal noise from the transformer. YES/NO',
            field=models.BooleanField(blank=True, db_column='check_8', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Check incoming supply voltage, current and keep the record',
            field=models.BooleanField(blank=True, db_column='check_2', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Check outgoing supply voltage and current and keep the record',
            field=models.BooleanField(blank=True, db_column='check_3', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Check proper supply for control and protection circuit',
            field=models.BooleanField(blank=True, db_column='check_6', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Check the display of RMU protection relay',
            field=models.BooleanField(blank=True, db_column='check_7', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Check the winding and core temperature reading on WTI relay and keep the record',
            field=models.BooleanField(blank=True, db_column='check_4', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='Clean the surrounding area of the job',
            field=models.BooleanField(blank=True, db_column='check_1', default='', null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='checked_by',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='month_year',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='operator',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='rating',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='sr_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='supervisor',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='devicemaintenancehistory',
            name='verified_by',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='devicemaintenancehistory',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='devicemaintenancehistory',
            name='remark',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
