# Generated by Django 4.1.7 on 2024-04-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_devicemaintenancehistory_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
