# Generated by Django 4.1.7 on 2023-08-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_alter_devices_maintenance'),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='data',
        ),
        migrations.AddField(
            model_name='notification',
            name='device',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devices.devices'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('MAINTENANCE_UPCOMMING', 'MAINTENANCE_UPCOMMING'), ('MAINTENANCE_DUE', 'MAINTENANCE_DUE'), ('MAINTENANCE_DONE', 'MAINTENANCE_DONE'), ('OTHER', 'OTHER')], default='', max_length=250),
        ),
    ]
