# Generated by Django 4.1.7 on 2023-09-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_data_notification_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='create_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('MAINTENANCE_UPCOMMING', 'MAINTENANCE_UPCOMMING'), ('MAINTENANCE_DUE', 'MAINTENANCE_DUE'), ('MAINTENANCE_DONE', 'MAINTENANCE_DONE'), ('OTHER', 'OTHER'), ('CRITICAL_FAILURE', 'CRITICAL_FAILURE')], default='', max_length=250),
        ),
    ]
